segmentacion/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^croquis_listado_api/',include('croquis_listado.api.urls',namespace='croquis_listado_api')),
    url(r'^croquis_listado/',include('croquis_listado.urls',namespace='croquis_listado')),
    url(r'^usuarios/',include('usuarios.urls',namespace='usuarios')),
    url(r'^usuarios/api/',include('usuarios.api.urls',namespace='usuarios_api')),
    #url(r'^rest-auth/', include('rest_auth.urls')),
    #url(r'^rest-auth/registration', include('rest_auth.registration.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/urls.py
from django.conf.urls import url
from django.urls import include, path
from usuarios.views import CerrarSesionView,LoginView
app_name = 'usuarios'


urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^cerrar-sesion/$', CerrarSesionView.as_view(), name='cerrar-sesion'),
    #url(r'^rest-auth/', include('rest_auth.urls')),
]

templates/layouts/navbar-header.html
{% load  staticfiles %}
<div class="navbar-header">
    <!--<a class="navbar-brand" href="/">
        <!--<img src="{% static 'custom' %}/img/inei_logo.jpg" alt="">
        <img src="{% static 'custom' %}/img/logo_censo.png" alt="">-->
    <!--</a>-->

    <ul class="nav navbar-nav pull-right visible-xs-block">
        <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
        <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
    </ul>

</div>
<div class="navbar-collapse collapse" id="navbar-mobile">

    <ul class="nav navbar-nav">
        <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
        <li>
            <!--<h5>{{ CLIENTE_TITULO|safe }}</h5>-->
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown dropdown-user">

            {% if request.user.is_authenticated %}
            <a class="dropdown-toggle" data-toggle="dropdown">
                <img src="assets/images/placeholder.jpg" alt="">
                <span>{{ request.user.nombres }}</span>
                <i class="caret"></i>
            </a>



            <ul class="dropdown-menu dropdown-menu-right">
                <li><a href="{% url 'usuarios:cerrar-sesion' %}"><i class="icon-switch2"></i> Cerrar Sesion</a></li>
            </ul>



            {% else %}
               <!-- <ul class="dropdown-menu dropdown-menu-right">-->
                <li><a href="{% url 'usuarios:login' %}"><i class="icon-user-plus"></i> Login</a></li>
                <!--</ul>-->

            {% endif %}



        </li>

    </ul>
</div>

templates/layouts/sidebar.html
{% load  staticfiles %}
{% load mptt_tags %}
<!-- Main sidebar -->
<div class="sidebar sidebar-main ">
    <div class="sidebar-content">
        <!-- Main navigation -->
      					<div class="sidebar-category sidebar-category-visible">
						<div class="category-content no-padding">
							<ul class="navigation navigation-main navigation-accordion">

								<!-- Main -->
								<li class="navigation-header"><span>Main</span> <i class="icon-menu" title="Main pages"></i></li>
								<!--<li><a href="index.html"><i class="icon-home4"></i> <span>Dashboard</span></a></li>-->




								</li>
                            </ul>
                        </div>
                        </div>
        <!-- /main navigation -->

        <!-- User menu -->

        <!-- /user menu -->
    </div>
</div>
<!-- /main sidebar -->